version: "3.8"

services:
  builder:
    platform: linux/amd64
    container_name: recast-wasm-builder
    build: .
    volumes:
      - ./build:/workspace/build
      - /emsdk/upstream/emscripten/cache
    command: sh build.sh
